spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/BankAppDB?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: pass@word1
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8082
management: 
  endpoints: 
    enabled-by-default: false
    web: 
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true                        