spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/BankAppDB?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: pass@word1
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8081      
management: 
  endpoints: 
    enabled-by-default: false
    web: 
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true       
jwt: 
  secret: bankapp672102          